workspaceId: izYOCQB
version:
  type: export
  exportedAt: '2026-07-15T14:19:26.605Z'
  name: 7-15-2026.1-1784125165117
checksums:
  automations:
    toremove: 588a778b849ae86731eda5a6fac14ea9
  imports: {}
  pages: {}
groups:
  - test
app:
  slug: app to remove 2
  name: app to remove
  description: description
